# Site settings
title: Kris Bogdanov 👋
email:
author:
description:
url: https://kris.ventures
twitter_username: kris_bogdanov

# category pages
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Build settings
permalink: /blog/:slug/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-sitemap

jekyll_timeago:
  depth: 1

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

markdown: kramdown
highlighter: rouge

include: 
    - _redirects
    - _pages
    - _category
