# Site settings
title: Podcasts Notes 👋
email: 
author: Insight Nderitu
description: Podcast Notes Ideas and Tools
url: https://podcastsnotes.com
twitter_username: podcastsnotes
instagram_username: podcastsnotes


# category pages
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Build settings
permalink: /notes/:slug/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-sitemap

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

markdown: kramdown
highlighter: rouge

include: 
    - _redirects
    - _pages
    - _category
