# Site settings
title: Kris Bogdanov 👋
email:
author:
description:
url: https://kris.ventures
twitter_username: kris_bogdanov

# Build settings
permalink: /blog/:slug/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-sitemap

include: ["_pages"]

jekyll_timeago:
  depth: 1

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

markdown: kramdown
highlighter: rouge
